/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todoliste;

import com.mysql.cj.jdbc.exceptions.CommunicationsException;
import java.awt.Color;
import static todoliste.JDBC.isOnline;

/**
 *
 * @author Benjamin O. Høj
 */
public class CreateNewTeam extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public CreateNewTeam() {
        initComponents();
        creationStatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamName = new javax.swing.JTextField();
        lblTeamName = new javax.swing.JLabel();
        createTeam = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        creationStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create team");
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(799, 371));
        setMaximumSize(new java.awt.Dimension(161, 200));
        setMinimumSize(new java.awt.Dimension(161, 200));
        setName("Create team"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        teamName.setText("A team name");
        teamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameActionPerformed(evt);
            }
        });
        getContentPane().add(teamName);
        teamName.setBounds(21, 50, 120, 30);

        lblTeamName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeamName.setText("Team name:");
        getContentPane().add(lblTeamName);
        lblTeamName.setBounds(1, 30, 160, 14);

        createTeam.setText("Create team");
        createTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamActionPerformed(evt);
            }
        });
        getContentPane().add(createTeam);
        createTeam.setBounds(21, 90, 120, 23);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(21, 120, 120, 23);

        creationStatus.setForeground(new java.awt.Color(255, 0, 0));
        creationStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creationStatus.setText("Illegal team name!");
        getContentPane().add(creationStatus);
        creationStatus.setBounds(1, 16, 160, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamActionPerformed
        if (teamName.getText().matches("[A-Za-z0-9+$&+,:=?@#|<>.^*\\s/%!\\-_()¤ÆØÅæøå/¨]+$")){
            try{
                   JDBC.createTeam(teamName.getText());
                   creationStatus.setText("Team created!");
                    creationStatus.setForeground(Color.green);
                    creationStatus.setVisible(true);
            }
            catch(CommunicationsException e){
                System.out.println("JDBC er offline");
                isOnline = false;
                Hovedvindue.closeWindows();
                LoginVindue login = new LoginVindue();
                login.setVisible(true);
            }
            catch(Exception e){
                System.out.println("Fejl i skabelse af hold");
            }
        }
        else{
            creationStatus.setText("Illegal team name!");
            creationStatus.setForeground(Color.red);
            creationStatus.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_createTeamActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void teamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton createTeam;
    private javax.swing.JLabel creationStatus;
    private javax.swing.JLabel lblTeamName;
    private javax.swing.JTextField teamName;
    // End of variables declaration//GEN-END:variables
}
